/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as PressRouteImport } from './routes/press'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedIntelligenceRouteRouteImport } from './routes/_authenticated/intelligence/route'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as IntelligenceIndexRouteImport } from './routes/intelligence.index'
import { Route as IntelligenceDashboardRouteImport } from './routes/intelligence.dashboard'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as WorkIndexRouteImport } from './routes/work.index'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedIntelligenceAskRouteImport } from './routes/_authenticated/intelligence/ask'
import { Route as AuthenticatedIntelligenceCompetitorsRouteImport } from './routes/_authenticated/intelligence/competitors'
import { Route as AuthenticatedIntelligenceMentionsRouteImport } from './routes/_authenticated/intelligence/mentions'
import { Route as AuthenticatedIntelligenceOverviewRouteImport } from './routes/_authenticated/intelligence/overview'
import { Route as AuthenticatedIntelligenceReportsRouteImport } from './routes/_authenticated/intelligence/reports'
import { Route as AuthenticatedIntelligenceTopicsRouteImport } from './routes/_authenticated/intelligence/topics'
import { Route as AuthenticatedIntelligenceIntegrationsIndexRouteImport } from './routes/_authenticated/intelligence/integrations.index'
import { Route as AuthenticatedIntelligenceProjectsIndexRouteImport } from './routes/_authenticated/intelligence/projects.index'
import { Route as AuthenticatedIntelligenceProjectsIdRouteImport } from './routes/_authenticated/intelligence/projects.$id'
import { Route as AuthenticatedIntelligenceUsersIndexRouteImport } from './routes/_authenticated/intelligence/users.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntelligenceRouteRoute =
  AuthenticatedIntelligenceRouteRouteImport.update({
    id: '/intelligence',
    path: '/intelligence',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceIndexRoute = IntelligenceIndexRouteImport.update({
  id: '/intelligence/',
  path: '/intelligence/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceDashboardRoute = IntelligenceDashboardRouteImport.update({
  id: '/intelligence/dashboard',
  path: '/intelligence/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkIndexRoute = WorkIndexRouteImport.update({
  id: '/work/',
  path: '/work/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedIntelligenceAskRoute =
  AuthenticatedIntelligenceAskRouteImport.update({
    id: '/ask',
    path: '/ask',
    getParentRoute: () => AuthenticatedIntelligenceRouteRoute,
  } as any)
const AuthenticatedIntelligenceCompetitorsRoute =
  AuthenticatedIntelligenceCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedIntelligenceRouteRoute,
  } as any)
const AuthenticatedIntelligenceMentionsRoute =
  AuthenticatedIntelligenceMentionsRouteImport.update({
    id: '/mentions',
    path: '/mentions',
    getParentRoute: () => AuthenticatedIntelligenceRouteRoute,
  } as any)
const AuthenticatedIntelligenceOverviewRoute =
  AuthenticatedIntelligenceOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedIntelligenceRouteRoute,
  } as any)
const AuthenticatedIntelligenceReportsRoute =
  AuthenticatedIntelligenceReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedIntelligenceRouteRoute,
  } as any)
const AuthenticatedIntelligenceTopicsRoute =
  AuthenticatedIntelligenceTopicsRouteImport.update({
    id: '/topics',
    path: '/topics',
    getParentRoute: () => AuthenticatedIntelligenceRouteRoute,
  } as any)
const AuthenticatedIntelligenceIntegrationsIndexRoute =
  AuthenticatedIntelligenceIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthenticatedIntelligenceRouteRoute,
  } as any)
const AuthenticatedIntelligenceProjectsIndexRoute =
  AuthenticatedIntelligenceProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedIntelligenceRouteRoute,
  } as any)
const AuthenticatedIntelligenceProjectsIdRoute =
  AuthenticatedIntelligenceProjectsIdRouteImport.update({
    id: '/projects/$id',
    path: '/projects/$id',
    getParentRoute: () => AuthenticatedIntelligenceRouteRoute,
  } as any)
const AuthenticatedIntelligenceUsersIndexRoute =
  AuthenticatedIntelligenceUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => AuthenticatedIntelligenceRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/press': typeof PressRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/intelligence': typeof AuthenticatedIntelligenceRouteRouteWithChildren
  '/insights/$slug': typeof InsightsSlugRoute
  '/intelligence/dashboard': typeof IntelligenceDashboardRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/insights/': typeof InsightsIndexRoute
  '/intelligence/': typeof IntelligenceIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/intelligence/ask': typeof AuthenticatedIntelligenceAskRoute
  '/intelligence/competitors': typeof AuthenticatedIntelligenceCompetitorsRoute
  '/intelligence/mentions': typeof AuthenticatedIntelligenceMentionsRoute
  '/intelligence/overview': typeof AuthenticatedIntelligenceOverviewRoute
  '/intelligence/reports': typeof AuthenticatedIntelligenceReportsRoute
  '/intelligence/topics': typeof AuthenticatedIntelligenceTopicsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/intelligence/projects/$id': typeof AuthenticatedIntelligenceProjectsIdRoute
  '/intelligence/integrations/': typeof AuthenticatedIntelligenceIntegrationsIndexRoute
  '/intelligence/projects/': typeof AuthenticatedIntelligenceProjectsIndexRoute
  '/intelligence/users/': typeof AuthenticatedIntelligenceUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/press': typeof PressRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/intelligence': typeof IntelligenceIndexRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/intelligence/dashboard': typeof IntelligenceDashboardRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/insights': typeof InsightsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/work': typeof WorkIndexRoute
  '/intelligence/ask': typeof AuthenticatedIntelligenceAskRoute
  '/intelligence/competitors': typeof AuthenticatedIntelligenceCompetitorsRoute
  '/intelligence/mentions': typeof AuthenticatedIntelligenceMentionsRoute
  '/intelligence/overview': typeof AuthenticatedIntelligenceOverviewRoute
  '/intelligence/reports': typeof AuthenticatedIntelligenceReportsRoute
  '/intelligence/topics': typeof AuthenticatedIntelligenceTopicsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/intelligence/projects/$id': typeof AuthenticatedIntelligenceProjectsIdRoute
  '/intelligence/integrations': typeof AuthenticatedIntelligenceIntegrationsIndexRoute
  '/intelligence/projects': typeof AuthenticatedIntelligenceProjectsIndexRoute
  '/intelligence/users': typeof AuthenticatedIntelligenceUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/press': typeof PressRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/team': typeof TeamRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/intelligence': typeof AuthenticatedIntelligenceRouteRouteWithChildren
  '/insights/$slug': typeof InsightsSlugRoute
  '/intelligence/dashboard': typeof IntelligenceDashboardRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/work/$slug': typeof WorkSlugRoute
  '/insights/': typeof InsightsIndexRoute
  '/intelligence/': typeof IntelligenceIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/work/': typeof WorkIndexRoute
  '/_authenticated/intelligence/ask': typeof AuthenticatedIntelligenceAskRoute
  '/_authenticated/intelligence/competitors': typeof AuthenticatedIntelligenceCompetitorsRoute
  '/_authenticated/intelligence/mentions': typeof AuthenticatedIntelligenceMentionsRoute
  '/_authenticated/intelligence/overview': typeof AuthenticatedIntelligenceOverviewRoute
  '/_authenticated/intelligence/reports': typeof AuthenticatedIntelligenceReportsRoute
  '/_authenticated/intelligence/topics': typeof AuthenticatedIntelligenceTopicsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/intelligence/projects/$id': typeof AuthenticatedIntelligenceProjectsIdRoute
  '/_authenticated/intelligence/integrations/': typeof AuthenticatedIntelligenceIntegrationsIndexRoute
  '/_authenticated/intelligence/projects/': typeof AuthenticatedIntelligenceProjectsIndexRoute
  '/_authenticated/intelligence/users/': typeof AuthenticatedIntelligenceUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/press'
    | '/pricing'
    | '/privacy'
    | '/search'
    | '/team'
    | '/terms'
    | '/admin'
    | '/intelligence'
    | '/insights/$slug'
    | '/intelligence/dashboard'
    | '/services/$slug'
    | '/work/$slug'
    | '/insights/'
    | '/intelligence/'
    | '/services/'
    | '/work/'
    | '/intelligence/ask'
    | '/intelligence/competitors'
    | '/intelligence/mentions'
    | '/intelligence/overview'
    | '/intelligence/reports'
    | '/intelligence/topics'
    | '/admin/'
    | '/intelligence/projects/$id'
    | '/intelligence/integrations/'
    | '/intelligence/projects/'
    | '/intelligence/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/press'
    | '/pricing'
    | '/privacy'
    | '/search'
    | '/team'
    | '/terms'
    | '/intelligence'
    | '/insights/$slug'
    | '/intelligence/dashboard'
    | '/services/$slug'
    | '/work/$slug'
    | '/insights'
    | '/services'
    | '/work'
    | '/intelligence/ask'
    | '/intelligence/competitors'
    | '/intelligence/mentions'
    | '/intelligence/overview'
    | '/intelligence/reports'
    | '/intelligence/topics'
    | '/admin'
    | '/intelligence/projects/$id'
    | '/intelligence/integrations'
    | '/intelligence/projects'
    | '/intelligence/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/press'
    | '/pricing'
    | '/privacy'
    | '/search'
    | '/team'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/intelligence'
    | '/insights/$slug'
    | '/intelligence/dashboard'
    | '/services/$slug'
    | '/work/$slug'
    | '/insights/'
    | '/intelligence/'
    | '/services/'
    | '/work/'
    | '/_authenticated/intelligence/ask'
    | '/_authenticated/intelligence/competitors'
    | '/_authenticated/intelligence/mentions'
    | '/_authenticated/intelligence/overview'
    | '/_authenticated/intelligence/reports'
    | '/_authenticated/intelligence/topics'
    | '/_authenticated/admin/'
    | '/_authenticated/intelligence/projects/$id'
    | '/_authenticated/intelligence/integrations/'
    | '/_authenticated/intelligence/projects/'
    | '/_authenticated/intelligence/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  PressRoute: typeof PressRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  TeamRoute: typeof TeamRoute
  TermsRoute: typeof TermsRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  IntelligenceDashboardRoute: typeof IntelligenceDashboardRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  WorkSlugRoute: typeof WorkSlugRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  IntelligenceIndexRoute: typeof IntelligenceIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  WorkIndexRoute: typeof WorkIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/intelligence': {
      id: '/_authenticated/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AuthenticatedIntelligenceRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/': {
      id: '/intelligence/'
      path: '/intelligence'
      fullPath: '/intelligence/'
      preLoaderRoute: typeof IntelligenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence/dashboard': {
      id: '/intelligence/dashboard'
      path: '/intelligence/dashboard'
      fullPath: '/intelligence/dashboard'
      preLoaderRoute: typeof IntelligenceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/': {
      id: '/work/'
      path: '/work'
      fullPath: '/work/'
      preLoaderRoute: typeof WorkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/intelligence/ask': {
      id: '/_authenticated/intelligence/ask'
      path: '/ask'
      fullPath: '/intelligence/ask'
      preLoaderRoute: typeof AuthenticatedIntelligenceAskRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRouteRoute
    }
    '/_authenticated/intelligence/competitors': {
      id: '/_authenticated/intelligence/competitors'
      path: '/competitors'
      fullPath: '/intelligence/competitors'
      preLoaderRoute: typeof AuthenticatedIntelligenceCompetitorsRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRouteRoute
    }
    '/_authenticated/intelligence/mentions': {
      id: '/_authenticated/intelligence/mentions'
      path: '/mentions'
      fullPath: '/intelligence/mentions'
      preLoaderRoute: typeof AuthenticatedIntelligenceMentionsRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRouteRoute
    }
    '/_authenticated/intelligence/overview': {
      id: '/_authenticated/intelligence/overview'
      path: '/overview'
      fullPath: '/intelligence/overview'
      preLoaderRoute: typeof AuthenticatedIntelligenceOverviewRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRouteRoute
    }
    '/_authenticated/intelligence/reports': {
      id: '/_authenticated/intelligence/reports'
      path: '/reports'
      fullPath: '/intelligence/reports'
      preLoaderRoute: typeof AuthenticatedIntelligenceReportsRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRouteRoute
    }
    '/_authenticated/intelligence/topics': {
      id: '/_authenticated/intelligence/topics'
      path: '/topics'
      fullPath: '/intelligence/topics'
      preLoaderRoute: typeof AuthenticatedIntelligenceTopicsRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRouteRoute
    }
    '/_authenticated/intelligence/integrations/': {
      id: '/_authenticated/intelligence/integrations/'
      path: '/integrations'
      fullPath: '/intelligence/integrations/'
      preLoaderRoute: typeof AuthenticatedIntelligenceIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRouteRoute
    }
    '/_authenticated/intelligence/projects/': {
      id: '/_authenticated/intelligence/projects/'
      path: '/projects'
      fullPath: '/intelligence/projects/'
      preLoaderRoute: typeof AuthenticatedIntelligenceProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRouteRoute
    }
    '/_authenticated/intelligence/projects/$id': {
      id: '/_authenticated/intelligence/projects/$id'
      path: '/projects/$id'
      fullPath: '/intelligence/projects/$id'
      preLoaderRoute: typeof AuthenticatedIntelligenceProjectsIdRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRouteRoute
    }
    '/_authenticated/intelligence/users/': {
      id: '/_authenticated/intelligence/users/'
      path: '/users'
      fullPath: '/intelligence/users/'
      preLoaderRoute: typeof AuthenticatedIntelligenceUsersIndexRouteImport
      parentRoute: typeof AuthenticatedIntelligenceRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedIntelligenceRouteRouteChildren {
  AuthenticatedIntelligenceAskRoute: typeof AuthenticatedIntelligenceAskRoute
  AuthenticatedIntelligenceCompetitorsRoute: typeof AuthenticatedIntelligenceCompetitorsRoute
  AuthenticatedIntelligenceMentionsRoute: typeof AuthenticatedIntelligenceMentionsRoute
  AuthenticatedIntelligenceOverviewRoute: typeof AuthenticatedIntelligenceOverviewRoute
  AuthenticatedIntelligenceReportsRoute: typeof AuthenticatedIntelligenceReportsRoute
  AuthenticatedIntelligenceTopicsRoute: typeof AuthenticatedIntelligenceTopicsRoute
  AuthenticatedIntelligenceProjectsIdRoute: typeof AuthenticatedIntelligenceProjectsIdRoute
  AuthenticatedIntelligenceIntegrationsIndexRoute: typeof AuthenticatedIntelligenceIntegrationsIndexRoute
  AuthenticatedIntelligenceProjectsIndexRoute: typeof AuthenticatedIntelligenceProjectsIndexRoute
  AuthenticatedIntelligenceUsersIndexRoute: typeof AuthenticatedIntelligenceUsersIndexRoute
}

const AuthenticatedIntelligenceRouteRouteChildren: AuthenticatedIntelligenceRouteRouteChildren =
  {
    AuthenticatedIntelligenceAskRoute: AuthenticatedIntelligenceAskRoute,
    AuthenticatedIntelligenceCompetitorsRoute:
      AuthenticatedIntelligenceCompetitorsRoute,
    AuthenticatedIntelligenceMentionsRoute:
      AuthenticatedIntelligenceMentionsRoute,
    AuthenticatedIntelligenceOverviewRoute:
      AuthenticatedIntelligenceOverviewRoute,
    AuthenticatedIntelligenceReportsRoute:
      AuthenticatedIntelligenceReportsRoute,
    AuthenticatedIntelligenceTopicsRoute: AuthenticatedIntelligenceTopicsRoute,
    AuthenticatedIntelligenceProjectsIdRoute:
      AuthenticatedIntelligenceProjectsIdRoute,
    AuthenticatedIntelligenceIntegrationsIndexRoute:
      AuthenticatedIntelligenceIntegrationsIndexRoute,
    AuthenticatedIntelligenceProjectsIndexRoute:
      AuthenticatedIntelligenceProjectsIndexRoute,
    AuthenticatedIntelligenceUsersIndexRoute:
      AuthenticatedIntelligenceUsersIndexRoute,
  }

const AuthenticatedIntelligenceRouteRouteWithChildren =
  AuthenticatedIntelligenceRouteRoute._addFileChildren(
    AuthenticatedIntelligenceRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedIntelligenceRouteRoute: typeof AuthenticatedIntelligenceRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedIntelligenceRouteRoute:
    AuthenticatedIntelligenceRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  PressRoute: PressRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  TeamRoute: TeamRoute,
  TermsRoute: TermsRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  IntelligenceDashboardRoute: IntelligenceDashboardRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  WorkSlugRoute: WorkSlugRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  IntelligenceIndexRoute: IntelligenceIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  WorkIndexRoute: WorkIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
